### ISSUE TITLE
How to create a unique user?

### ISSUE THREAD

**Issue by xwayway** [AxonFramework/AxonBank#18]
if i have a aggregate  **_User_** ，How to ensure its uniqueness when I am dealing with command？
import userQuerySide repository into userCommandSide ?

**Comment by smcvb** [comment]
Firstly, my apologies for the extremely late reply here, @xwayway.
What you're looking for is set-based validation, which works a little differently in CQRS/DDD/ES applications.
We drafted up a blog about this, which you can find [here](https://developer.axoniq.io/w/set-based-consistency-validation).
