### ISSUE TITLE
Read-only repository?

### ISSUE THREAD

**Issue by akullpp** [AxonFramework/AxonBank#24]
I've read the Axon documentation and looked at all provided sample projects, especially this one but one thing is still bothering me and is not explained as far as I see:

It is my understanding that in Axon you perform queries against a read database which represents the materialized view, e.g. a H2 that contains the latest `BankAccount` JPA entity. However if you have a Spring repository, e.g. `JpaRepository<BankAccount, Long>`, you also have the `save`-method which should only be used for commands. Shouldn't you split the repository into a read-only and write-only repository?

Could someone also point me the documentation what how Axon works with this repository? Because for an unitiated developer it looks like a "normal" JPA repository, i.e. the entity seems mutable and always up to date but from a theoretical perspective I expect an immutable entity in state 0 where a projection is created by applying all events, does this happen in the background?

What would happen if I update the entity with `JpaRepository#save` but not the aggregate? Will they be out of sync?

It seems that we have two sources of truth in this case, which shouldn't be the case theoretically.

**Comment by smcvb** [comment]
Hi @akullpp, I've noticed you have also opened a StackOverflow question for this. For reference to other potential readers, it can be found [here](https://stackoverflow.com/questions/62043799/axon-and-springs-repository-integration).

As stated there by @lfgcampos, you are likely looking at a discrepancy of the notion of [CQRS](https://axoniq.io/resources/cqrs).

Regardless of what the exact answer is, we aim to keep our GitHub repositories to feature requests, enhancement suggestions and bugs. For questions we point people towards our [User Group](https://groups.google.com/forum/#!forum/axonframework) or StackOverflow. As you already have created a StackOverflow question, I would suggest to validate whether @lfgcampos his answer is sufficient. If not, updating the StackOverflow question or the answer, would be the way to go.

Concluding, as this is a question, I will be closing it.
