### ISSUE TITLE
DestinationBankAccountNotFoundEvent not properly persisted when using JPA

### ISSUE THREAD

**Issue by stun4j** [AxonFramework/AxonBank#8]
hi
 I'm trying use **JpaSagaStore**&**JpaTransactionManager** to run the sample and mock an AggregateNotFoundException, but I got JDBC exception as below:
`
Hibernate: insert into domain_event_entry (event_identifier, meta_data, payload, payload_revision, payload_type, time_stamp, aggregate_identifier, sequence_number, type) values (?, ?, ?, ?, ?, ?, ?, ?, ?)
2017-02-07 12:11:29.489  WARN 33185 --- [nboundChannel-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1048, SQLState: 23000
2017-02-07 12:11:29.489 ERROR 33185 --- [nboundChannel-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column 'type' cannot be null
`

the direct step to mock the **AggregateNotFoundException** (then the **DestinationBankAccountNotFoundEvent** trigged),like below:
`
org.axonframework.samples.bank.command.BankAccountCommandHandler#handle(CreditDestinationBankAccountCommand command) {
omitted...
Aggregate<BankAccount> bankAccountAggregate = repository.load(command.getBankAccountId()+"aa");
omitted...
}
`

it seems somehow the domain-event not properly persisted,can anyone explain this?
btw,if I use **InMemorySagaStore**&**InMemoryEventStorageEngine**,this problem won't happen

**Comment by stun4j** [comment]
I think it's a bug of AXON 3.0

**Comment by abuijze** [comment]
Yes, it's in fact a bug which has been resolved in (I believe 3.0.1). Updating the version should resolve the issue.
I will update the sample code soon.
